name: ANVOL Update Stock

on:
  schedule:
    - cron: '0 */3 * * *'   # kas 3 valandas (UTC)
  workflow_dispatch:

jobs:
  update-anvol:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests lxml

      - name: Run ANVOL stock update script
        run: python update_anvol.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add updated_products.xml anvol.xml
          git commit -m "ANVOL automatinis likučių atnaujinimas: $(date '+%Y-%m-%d %H:%M:%S')" || echo "No changes"
          git push
