name: Run nonexiststock Script

on:
  schedule:
    # kasdien 06:00 UTC (~09:00 Lietuvos laiku žiemą)
    - cron: "0 4 * * *"
  workflow_dispatch:  # leidžia paleisti rankiniu būdu

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          # pridėk čia jei reikia kitų paketų

      - name: Run nonexiststock.py
        run: python nonexiststock.py

      - name: Upload updated_products.xml as artifact
        uses: actions/upload-artifact@v4
        with:
          name: updated-products
          path: updated_products.xml
          if-no-files-found: ignore
